# Generated by Django 4.1.3 on 2023-01-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Conversations',
        ),
    ]
